### Link: https://www.tutorialspoint.com/julia/julia_arrays.htm

In [2]:
student_name = "Ram"
roll_no = 15
marks_math = 9.5

9.5

In [2]:
#= This is an example to demonstrate the multi-line comments that tells 
us about tutorialspoint.com. At this website you can browse the best resource for Online Education.=#
print("www.tutorialspoint.com")

www.tutorialspoint.com

### Index: Julia - Arrays

In [3]:
# Creating Simple 1D Arrays
arr = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [4]:
array = Array{Int64}(undef, 3)

3-element Vector{Int64}:
 0
 0
 0

In [10]:
undef

UndefInitializer(): array initializer with undefined values

In [5]:
array = Array{Int64}(undef, 3, 3, 3)

3×3×3 Array{Int64, 3}:
[:, :, 1] =
 235790480         29         30
 235790544  235790608         30
         9  235790672  235790736

[:, :, 2] =
 235790800  235790864  0
        31  235790928  0
        32          0  0

[:, :, 3] =
 0  0  0
 0  0  0
 0  0  0

In [6]:
# Arrays of anything
[1, "TutorialsPoint.com", 5.5, tan, pi]

5-element Vector{Any}:
 1
  "TutorialsPoint.com"
 5.5
  tan (generic function with 12 methods)
 π = 3.1415926535897...

In [7]:
# Empty Arrays
A = Int64[]

Int64[]

In [8]:
A = String[]

String[]

In [9]:
# Creating 2D arrays & matrices

In [10]:
[1 2 3 4 5 6 7 8 9 10]

1×10 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10

In [11]:
[1 2 3 4 5 ; 6 7 8 9 10]

2×5 Matrix{Int64}:
 1  2  3  4   5
 6  7  8  9  10

In [14]:
collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [15]:
collect(1.5:5.5)

5-element Vector{Float64}:
 1.5
 2.5
 3.5
 4.5
 5.5

In [16]:
collect(0:5:50)

11-element Vector{Int64}:
  0
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50

In [17]:
# ellipsis(…) or splat operator

In [18]:
[0:10...]

11-element Vector{Int64}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [19]:
range(1, length=15, stop=150)

1.0:10.642857142857142:150.0

In [20]:
range(1, stop=150, step=10)

1:10:141

In [21]:
collect(range(1, length=15, stop=150))

15-element Vector{Float64}:
   1.0
  11.642857142857142
  22.285714285714285
  32.92857142857143
  43.57142857142857
  54.214285714285715
  64.85714285714286
  75.5
  86.14285714285714
  96.78571428571429
 107.42857142857143
 118.07142857142857
 128.71428571428572
 139.35714285714286
 150.0

In [22]:
# Creating arrays using comprehensions and generators

In [23]:
[n^2 for n in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [27]:
[n*m for n in 1:5, m in 1:10]

5×10 Matrix{Int64}:
 1   2   3   4   5   6   7   8   9  10
 2   4   6   8  10  12  14  16  18  20
 3   6   9  12  15  18  21  24  27  30
 4   8  12  16  20  24  28  32  36  40
 5  10  15  20  25  30  35  40  45  50

In [25]:
collect(n^2 for n in 1:5)

5-element Vector{Int64}:
  1
  4
  9
 16
 25

In [26]:
# Populating an Array

In [28]:
zeros(4,5)

4×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [29]:
zeros(Int64,4,5)

4×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [30]:
ones(4,5)

4×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [31]:
rand(4,5)

4×5 Matrix{Float64}:
 0.508853  0.374329  0.76019   0.0016759  0.875386
 0.819296  0.967428  0.59591   0.0911771  0.905632
 0.940644  0.833696  0.749208  0.125851   0.851672
 0.432553  0.686614  0.691395  0.523938   0.175401

In [32]:
randn(4,5)

4×5 Matrix{Float64}:
  1.67484   0.643436  -1.53193    -0.0161555  -1.36542
  0.925454  0.496542  -0.0272488  -0.12746    -1.23838
 -0.740038  2.66826    0.821769   -1.1277      0.437933
  0.447851  0.235445   0.211206    0.0913664  -0.673862

In [33]:
fill(100,5)

5-element Vector{Int64}:
 100
 100
 100
 100
 100

In [34]:
ABC = ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [35]:
fill!(ABC,100)

5-element Vector{Float64}:
 100.0
 100.0
 100.0
 100.0
 100.0

In [36]:
ABC

5-element Vector{Float64}:
 100.0
 100.0
 100.0
 100.0
 100.0

In [37]:
Array{Int64}(undef, 5)

5-element Vector{Int64}:
 282968144
 283130944
 283130944
 282968144
 216549184

In [38]:
# Arrays of arrays

In [39]:
ABC = Array[[3,4],[5,6]]

2-element Vector{Array}:
 [3, 4]
 [5, 6]

In [40]:
# with the help of Array constructor
Array[1:5,6:10]

2-element Vector{Array}:
 [1, 2, 3, 4, 5]
 [6, 7, 8, 9, 10]

In [41]:
# Copying arrays

In [42]:
A = collect(1:5);

In [43]:
B = similar(A)

5-element Vector{Int64}:
 1936921440
 1941598976
  244481536
 1960699872
  173932552

In [44]:
# Matrix Operations

In [45]:
[2 3 ; 4 5]

2×2 Matrix{Int64}:
 2  3
 4  5

In [46]:
Array[[3,4],[5,6]]

2-element Vector{Array}:
 [3, 4]
 [5, 6]

In [47]:
[[3,4] [5,6]]

2×2 Matrix{Int64}:
 3  5
 4  6

In [48]:
[[3 4] [5 6]]

1×4 Matrix{Int64}:
 3  4  5  6

In [49]:
# Accessing the contents of arrays

In [1]:
arr = [5,10,15,20,25,30,35,40,45,50]

10-element Vector{Int64}:
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50

In [51]:
arr[end]

50

In [52]:
arr[end-1]

45

In [53]:
arr[[2,5,6]]

3-element Vector{Int64}:
 10
 25
 30

In [4]:
arr[[true, false, true, true,true, false, false, true, true, false]]

6-element Vector{Int64}:
  5
 15
 20
 25
 40
 45

In [5]:
arr2 = [10 11 12; 13 14 15; 16 17 18]

3×3 Matrix{Int64}:
 10  11  12
 13  14  15
 16  17  18

In [6]:
arr2[2]

13

In [7]:
arr2[1,2]

11

In [8]:
arr2[1,3]

12

In [9]:
getindex(arr2,1,2)

11

In [10]:
getindex(arr2,2,3)

15

In [11]:
# Adding Elements

In [12]:
# At the end
push!(arr,55)

11-element Vector{Int64}:
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50
 55

In [13]:
# At the front
pushfirst!(arr,0)

12-element Vector{Int64}:
  0
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50
 55

In [14]:
arr

12-element Vector{Int64}:
  0
  5
 10
 15
 20
 25
 30
 35
 40
 45
 50
 55

In [15]:
splice!(arr,2:5,2:6)

4-element Vector{Int64}:
  5
 10
 15
 20

In [16]:
arr

13-element Vector{Int64}:
  0
  2
  3
  4
  5
  6
 25
 30
 35
 40
 45
 50
 55

In [17]:
# Removing Elements

In [18]:
pop!(arr)

55

In [19]:
arr

12-element Vector{Int64}:
  0
  2
  3
  4
  5
  6
 25
 30
 35
 40
 45
 50

In [20]:
popfirst!(arr)

0

In [21]:
arr

11-element Vector{Int64}:
  2
  3
  4
  5
  6
 25
 30
 35
 40
 45
 50

### Index: Julia - Tuples

In [22]:
tupl=(5,10,15,20,25,30)

(5, 10, 15, 20, 25, 30)

In [23]:
tupl

(5, 10, 15, 20, 25, 30)

In [24]:
tupl[3:end]

(15, 20, 25, 30)

In [25]:
tupl = ((1,2),(3,4))

((1, 2), (3, 4))

In [26]:
tupl[1]

(1, 2)

In [27]:
tupl[1][2]

2

In [28]:
tupl[2]=0

LoadError: MethodError: no method matching setindex!(::Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}}, ::Int64, ::Int64)

In [1]:
# Creating named tuples

In [12]:
names_shape = (:corner1, :corner2)
values_shape = ((100, 100), (200, 200))
shape_item2 = NamedTuple{names_shape}(values_shape)

(corner1 = (100, 100), corner2 = (200, 200))

In [14]:
typeof(names_shape)

Tuple{Symbol, Symbol}

In [15]:
typeof(values_shape)

Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}}

In [16]:
typeof(shape_item2)

NamedTuple{(:corner1, :corner2), Tuple{Tuple{Int64, Int64}, Tuple{Int64, Int64}}}

In [17]:
shape_item2.corner1

(100, 100)

In [18]:
# Keys and values in a single tuple

In [19]:
shape_item = (corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

(corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

In [20]:
shape_item.corner1

(1, 1)

In [21]:
(shape_item.center,shape_item.corner2)

((0, 0), (-1, -1))

In [22]:
c1, c2, center = shape_item

(corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

In [24]:
c2

(-1, -1)

In [25]:
# Combining two named tuples

In [26]:
colors_shape = (top = "red", bottom = "green")

(top = "red", bottom = "green")

In [27]:
shape_item = (corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

(corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0))

In [28]:
merge(shape_item, colors_shape)

(corner1 = (1, 1), corner2 = (-1, -1), center = (0, 0), top = "red", bottom = "green")

In [29]:
# Named tuples as keyword arguments

In [1]:
function ABC(x, y, z; a=10, b=20, c=30)
         println("x = $x, y = $y, z = $z; a = $a, b = $b, c = $c")
      end

ABC (generic function with 1 method)

In [2]:
options = (b = 200, c = 300)

(b = 200, c = 300)

In [3]:
ABC(1, 2, 3; options...)

x = 1, y = 2, z = 3; a = 10, b = 200, c = 300


In [4]:
ABC(1, 2, 3; b = 1000_000, options...)

x = 1, y = 2, z = 3; a = 10, b = 200, c = 300


In [5]:
ABC(1, 2, 3; options..., b= 1000_000)

x = 1, y = 2, z = 3; a = 10, b = 1000000, c = 300


### Index: Integers and Floating-Point Numbers

In [6]:
Sys.WORD_SIZE

64

In [7]:
typeof(100)

Int64

In [8]:
# Overflow behavior

In [11]:
A = typemax(Int64)

9223372036854775807

In [12]:
A + 1

-9223372036854775808

In [13]:
A + 1 == typemin(Int64)

true

In [14]:
10^19

-8446744073709551616

In [15]:
big(10)^19

10000000000000000000

In [16]:
big(10^19)

-8446744073709551616

In [17]:
# Division errors

In [18]:
mod(1, 0)

LoadError: DivideError: integer division error

In [19]:
rem(1, 0)

LoadError: DivideError: integer division error

In [20]:
# Floating-point numbers

In [21]:
1.0

1.0

In [22]:
-1.256

-1.256

In [23]:
2e11

2.0e11

In [24]:
3.6e-5

3.6e-5

In [28]:
0.5f-5

5.0f-6

In [29]:
ans

5.0f-6

In [30]:
typeof(ans)

Float32

In [31]:
1.5f0

1.5f0

In [32]:
typeof(ans)

Float32

In [33]:
0.0 == -0.0

true

In [34]:
bitstring(0.0)

"0000000000000000000000000000000000000000000000000000000000000000"

In [35]:
bitstring(-0.0)

"1000000000000000000000000000000000000000000000000000000000000000"

In [36]:
bitstring(0.0) == bitstring(-0.0)

false

In [37]:
# Special floating-point values

In [38]:
(typemin(Float16),typemax(Float16))

(-Inf16, Inf16)

In [39]:
(typemin(Float32),typemax(Float32))

(-Inf32, Inf32)

In [40]:
(typemin(Float64),typemax(Float64))

(-Inf, Inf)

In [41]:
# Machine epsilon

In [42]:
eps(Float32)

1.1920929f-7

In [43]:
eps(Float64)

2.220446049250313e-16

In [44]:
# Rounding modes

In [45]:
BigFloat("1.510564889",2,RoundNearest)

1.5

 ### Index: Rational and Complex Numbers

In [46]:
# Rational Numbers

In [47]:
4//5

4//5

In [48]:
numerator(8//9)

8

In [49]:
denominator(8//9)

9

In [50]:
# Converting to floating-point numbers

In [51]:
float(2//3)

0.6666666666666666

In [52]:
A = 20; B = 30;

In [53]:
isequal(float(A//B), A/B)

true

In [1]:
# Complex Numbers

In [2]:
2+3im

2 + 3im

In [3]:
# Performing Standard arithmetic operations

In [4]:
(2 + 3im)*(1 - 2im)

8 - 1im

In [5]:
(2 + 3im)/(1 - 2im)

-0.8 + 1.4im

In [6]:
(2 + 3im)+(1 - 2im)

3 + 1im

In [7]:
(2 + 3im)-(1 - 2im)

1 + 5im

In [8]:
(2 + 3im)^2

-5 + 12im

In [9]:
(2 + 3im)^2.6

-23.375430842463754 + 15.527174176755075im

In [10]:
2(2 + 3im)^-2.0

-0.059171597633136105 - 0.14201183431952663im

In [11]:
# Combining different operands

In [12]:
2(2 + 3im)

4 + 6im

In [13]:
(2 + 3im)-1

1 + 3im

In [14]:
(2 + 3im)+0.7

2.7 + 3.0im

In [15]:
(2 + 3im)-0.7im

2.0 + 2.3im

In [16]:
0.89(2 + 3im)

1.78 + 2.67im

In [17]:
(2 + 3im)/2

1.0 + 1.5im

In [18]:
(2 + 3im)/(1-3im)

-0.7000000000000001 + 0.8999999999999999im

In [19]:
3im^3

0 - 3im

In [20]:
1+2/5im

1.0 - 0.4im

In [21]:
# Functions to manipulate complex values

In [22]:
real(4+7im)

4

In [23]:
imag(4+7im)

7

In [24]:
conj(4+7im)

4 - 7im

In [25]:
abs(4+7im)

8.06225774829855

In [26]:
abs2(4+7im)

65

In [27]:
angle(4+7im)

1.0516502125483738

In [28]:
sqrt(7im)

1.8708286933869707 + 1.8708286933869707im

In [29]:
sqrt(4+7im)

2.455835677350843 + 1.4251767869809258im

In [30]:
cos(4+7im)

-358.40393224005317 + 414.96701031076253im

In [31]:
exp(4+7im)

41.16166839296141 + 35.87025288661357im

In [32]:
sinh(4+7im)

20.573930095756726 + 17.941143007955223im

### Index: Julia - Basic Operators

In [33]:
2+20-5

17

In [34]:
3-8

-5

In [35]:
50*2/10

10.0

In [36]:
23%2

1

In [37]:
2^4

16

In [38]:
# Bitwise Operators

In [40]:
~1009

-1010

In [41]:
12&23

4

In [42]:
12 | 23

31

In [43]:
12 ⊻ 23

27

In [44]:
xor(12, 23)

27

In [46]:
~UInt32(12)

0xfffffff3

In [47]:
~UInt8(12)

0xf3

In [48]:
# Updating Operators

In [49]:
A = 100

100

In [50]:
A +=100

200

In [51]:
# Vectorized “dot” Operators

In [52]:
[1, 2, 3].^2

3-element Vector{Int64}:
 1
 4
 9

In [54]:
# Numeric Comparisons Operators
==, <, <=, >, >=

(==, <, <=, >, >=)

In [55]:
# Chaining Comparisons

In [56]:
100 < 200 <= 200 < 300 == 300 > 200 >= 100 == 100 < 300 != 500

true

In [57]:
M(a) = (println(a); a)

M (generic function with 1 method)

In [58]:
M(1) < M(2) <= M(3)

2
1
3


true

### Index: Julia - Basic Mathematical Functions

In [59]:
Int8(110)

110

In [60]:
Int8(128)

LoadError: InexactError: trunc(Int8, 128)

In [61]:
Int8(110.0)

110

In [62]:
Int8(3.14)

LoadError: InexactError: Int8(3.14)

In [63]:
110%Int8

110

In [64]:
128%Int8

-128

In [65]:
round(Int8, 110.35)

110

In [66]:
round(Int8, 127.52)

LoadError: InexactError: trunc(Int8, 128.0)

In [1]:
# Rounding functions

In [2]:
round(3.8)

4.0

In [3]:
round(Int, 3.8)

4

In [4]:
floor(3.8)

3.0

In [5]:
floor(Int, 3.8)

3

In [6]:
ceil(3.8)

4.0

In [7]:
ceil(Int, 3.8)

4

In [8]:
trunc(3.8)

3.0

In [9]:
trunc(Int, 3.8)

3

In [12]:
# Division functions

In [1]:
div(11, 4)

2

In [2]:
div(7, 4)

1

In [3]:
div(-7, 4)

-1

In [4]:
fld(11, 4)

2

In [5]:
fld(-5,3)

-2

In [6]:
fld(7.5,3.3)

2.0

In [7]:
cld(7.5,3.3)

3.0

In [8]:
# couldn't understand
mod(5, 0:2)

2

In [10]:
typeof(0:2)

UnitRange{Int64}

In [11]:
mod(3, 0:2)

0

In [12]:
mod(8.9,2)

0.9000000000000004

In [13]:
rem(8,4)

0

In [14]:
rem(9,4)

1

In [15]:
mod2pi(7*pi/5)

4.39822971502571

In [16]:
divrem(8,3)

(2, 2)

In [17]:
fldmod(12,4)

(3, 0)

In [18]:
fldmod(13,4)

(3, 1)

In [19]:
mod1(5,4)

1

In [20]:
gcd(6,0)

6

In [21]:
gcd(1//3,2//3)

1//3

In [22]:
lcm(1//3,2//3)

2//3

In [23]:
# Sign and Absolute value functions

In [24]:
 abs(-7)

7

In [25]:
abs(5+3im)

5.830951894845301

In [26]:
abs2(-7)

49

In [27]:
abs2(5+3im)

34

In [28]:
copysign(5,-10)

-5

In [29]:
copysign(-5,10)

5

In [30]:
sign(5)

1

In [31]:
sign(-5)

-1

In [32]:
signbit(-5)

true

In [33]:
signbit(5)

false

In [34]:
flipsign(5,10)

5

In [35]:
flipsign(5,-10)

-5

In [36]:
# Power, Logs, and Roots

In [37]:
sqrt(49)

7.0

In [38]:
sqrt(-49)

LoadError: DomainError with -49.0:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).

In [39]:
cbrt(8)

2.0

In [40]:
cbrt(-8)

-2.0

In [41]:
a = Int64(5)^10;

In [42]:
hypot(a, a)

1.3810679320049757e7

In [43]:
exp(5.0)

148.4131591025766

In [44]:
expm1(10)

22025.465794806718

In [45]:
expm1(1.0)

1.7182818284590453

In [46]:
ldexp(4.0, 2)

16.0

In [47]:
log(5,2)

0.43067655807339306

In [48]:
log(4,2)

0.5

In [49]:
log(4)

1.3862943611198906

In [50]:
log2(4)

2.0

In [51]:
log10(4)

0.6020599913279624

In [52]:
log1p(4)

1.6094379124341003

In [53]:
log1p(-2)

LoadError: DomainError with -2.0:
log1p will only return a complex result if called with a complex argument. Try log1p(Complex(x)).

In [54]:
significand(15.2)/10.2

0.18627450980392157

In [55]:
# Trigonometric and hyperbolic functions

In [56]:
cos(56)

0.853220107722584

In [57]:
cosd(56)

0.5591929034707468

### Index: Julia - Strings

In [58]:
# Characters

In [59]:
'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [60]:
typeof(ans)

Char

In [61]:
Int('a')

97

In [62]:
typeof(ans)

Int64

In [63]:
Char(97)

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [64]:
'X' < 'x'

true

In [65]:
'X' <= 'x' <= 'Y'

false

In [66]:
'X' <= 'a' <= 'Y'

false

In [67]:
'a' <= 'x' <= 'Y'

false

In [68]:
'A' <= 'X' <= 'Y'

true

In [69]:
'x' - 'b'

22

In [70]:
'x' + 1

'y': ASCII/Unicode U+0079 (category Ll: Letter, lowercase)

In [71]:
Int('x')

120

In [72]:
Int('y')

121

In [73]:
# Delimited by double quotes or triple double quotes

In [74]:
str = "This is Julia Programming Language.\n"

"This is Julia Programming Language.\n"

In [75]:
"""See the "quote" characters"""

"See the \"quote\" characters"

In [76]:
# Performing arithmetic and other operations with end

In [77]:
str[end-1]

'.': ASCII/Unicode U+002E (category Po: Punctuation, other)

In [78]:
str[end÷2]

'g': ASCII/Unicode U+0067 (category Ll: Letter, lowercase)

In [79]:
str[6:9]

"is J"

In [80]:
substr = SubString(str, 1, 4)

"This"

In [81]:
typeof(substr)

SubString{String}

In [82]:
# Unicode and UTF-8

In [83]:
s = "\u2200 x \u2203 y"

"∀ x ∃ y"

In [87]:
"\u2205 x \u2203 y"

"∅ x ∃ y"

In [88]:
s[1]

'∀': Unicode U+2200 (category Sm: Symbol, math)

In [89]:
s[2]

LoadError: StringIndexError: invalid index [2], valid nearby indices [1]=>'∀', [4]=>' '

In [90]:
# String Concatenation

In [91]:
A = "Hello"

"Hello"

In [92]:
B = "Julia Programming Language"

"Julia Programming Language"

In [93]:
string(A, ", ", B, ".\n")

"Hello, Julia Programming Language.\n"

In [94]:
A * ", " * B * ".\n"

"Hello, Julia Programming Language.\n"

In [95]:
# Interpolation

In [96]:
"$A, $B.\n"

"Hello, Julia Programming Language.\n"

In [97]:
"100 + 10 = $(100 + 10)"

"100 + 10 = 110"

In [98]:
print("His salary is \$5000 per month.\n")

His salary is $5000 per month.


In [99]:
# Triple-quoted strings

In [101]:
"""See the "quote" characters"""

"See the \"quote\" characters"

In [102]:
str = """
                  This is,
                  Julia Programming Language.
               """

"   This is,\n   Julia Programming Language.\n"

In [103]:
""" This
             is
               Julia Programming Language"""

" This\nis\n  Julia Programming Language"

In [104]:
# Common String Operations

In [105]:
"abababab" < "Tutorialspoint"

false

In [106]:
"abababab" > "Tutorialspoint"

true

In [107]:
"abababab" == "Tutorialspoint"

false

In [108]:
"abababab" != "Tutorialspoint"

true

In [109]:
"100 + 10 = 110" == "100 + 10 = $(100 + 10)"

true

In [111]:
"a" < "b"

true

In [112]:
"b" < "aa"

false

In [113]:
# Search operators

In [114]:
findfirst(isequal('o'), "Tutorialspoint")

4

In [115]:
findlast(isequal('o'), "Tutorialspoint")

11

In [116]:
findnext(isequal('o'), "Tutorialspoint", 1)

4

In [117]:
findnext(isequal('o'), "Tutorialspoint", 5)

11

In [118]:
findprev(isequal('o'), "Tutorialspoint", 5)

4

In [119]:
occursin("Julia", "This is, Julia Programming.")

true

In [120]:
occursin("T", "Tutorialspoint")

true

In [121]:
occursin("Z", "Tutorialspoint")

false

In [122]:
repeat("Tutorialspoint.com ", 5)

"Tutorialspoint.com Tutorialspoint.com Tutorialspoint.com Tutorialspoint.com Tutorialspoint.com "

In [123]:
join(["TutorialsPoint","com"], " . ")

"TutorialsPoint . com"

In [124]:
# Non-standard String Literals

In [125]:
# Raw String Literals

In [126]:
println(raw"\\ \\\"")

\\ \"


In [133]:
println(raw"\\\ \\"")

LoadError: syntax: cannot juxtapose string literal

In [134]:
b"DATA\xff\u2200"

8-element Base.CodeUnits{UInt8, String}:
 0x44
 0x41
 0x54
 0x41
 0xff
 0xe2
 0x88
 0x80

In [135]:
isvalid("DATA\xff\u2200")

false

In [136]:
# Version Number Literals

In [139]:
print(VERSION)
if v"1.0" <= VERSION < v"0.9-"
    # you need to do something specific to 1.0 release series
    print(VERSION)
    end

1.7.2

In [140]:
# Regular Expressions

In [141]:
r"^\s*(?:#|$)"

r"^\s*(?:#|$)"

In [142]:
typeof(ans)

Regex

In [143]:
occursin(r"^\s*(?:#|$)", "not a comment")

false

In [144]:
occursin(r"^\s*(?:#|$)", "# a comment")

true

 ### Index: Julia - Functions

In [1]:
f(a) = a * a

f (generic function with 1 method)

In [2]:
func(x, y) = sqrt(x^2 + y^2)

func (generic function with 1 method)

In [3]:
func(5, 4)

6.4031242374328485

In [6]:
function bills(money)
      if money < 0
         return false
      else
         return true
      end
   end

bills (generic function with 1 method)

In [7]:
bills(50)

true

In [8]:
bills(-50)

false

In [48]:
function mul(x,y)
    x+y, x*y
    end

mul (generic function with 1 method)

In [49]:
mul(5, 10)

(15, 50)

In [50]:
# Optional Arguments

In [53]:
function pos(ax, by, cz=0)
    println("$ax, $by, $cz")
    end

pos (generic function with 2 methods)

In [54]:
pos(10, 30)

10, 30, 0


In [55]:
pos(10, 30, 50)

10, 30, 50


In [56]:
# Keyword Arguments

In [57]:
function foo(a, b ; c = 10, d = "hi")
    println("a is $a")
    println("b is $b")
    return "c => $c, d => $d"
    end

foo (generic function with 1 method)

In [58]:
foo(100,20)

a is 100
b is 20


"c => 10, d => hi"

In [59]:
foo("Hello", "Tutorialspoint", c=pi, d=22//7)

a is Hello
b is Tutorialspoint


"c => π, d => 22//7"

In [61]:
foo("Hello", "Tutorialspoint", d=pi, c=22//7)

a is Hello
b is Tutorialspoint


"c => 22//7, d => π"

In [66]:
foo(c=pi, d =22/7, "Hello", "Tutorialspoint")

a is Hello
b is Tutorialspoint


"c => π, d => 3.142857142857143"

In [64]:
function foo(;a, b, c = 10, d = "hi")
    println("a is $a")
    println("b is $b")
    return "c => $c, d => $d"
    end

foo (generic function with 4 methods)

In [65]:
foo(b="Hello", a="Tutorialspoint", c=pi, d=22//7)

a is Tutorialspoint
b is Hello


"c => π, d => 22//7"

In [67]:
# Anonymous Functions

In [68]:
A -> A^3 + 3A - 3

#3 (generic function with 1 method)

In [69]:
map(A -> A^3 + 3A - 3, [10,3,-2])

3-element Vector{Int64}:
 1027
   33
  -17

In [70]:
A

LoadError: UndefVarError: A not defined

In [71]:
# Recursive Functions

In [72]:
function add(x)
      Y = x * 2
      function add1(Y)
         Y += 1
      end
      add1(Y)
      end

add (generic function with 1 method)

In [73]:
add(10)

21

In [74]:
sum(x) = x > 1 ? sum(x-1) + x : x

sum (generic function with 1 method)

In [75]:
sum(2)

3

In [76]:
fib(x) = x < 2 ? x : fib(x-1) + fib(x-2)

fib (generic function with 1 method)

In [80]:
fib(3)

2

In [81]:
# Map

In [82]:
map(A -> A^3 + 3A - 3, [10,3,-2])

3-element Vector{Int64}:
 1027
   33
  -17

In [83]:
# Filter

In [84]:
array = Int[1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [85]:
filter(x -> x % 2 == 0, array)

1-element Vector{Int64}:
 2

In [86]:
# Generic Functions

In [87]:
# Multiple dispatch

In [14]:
foo(A, B) = "base case"

foo (generic function with 5 methods)

In [15]:
foo(A::Number, B::Number) = "A and B are both numbers"

foo (generic function with 5 methods)

In [16]:
foo(A::Number, B) = "A is a number"

foo (generic function with 5 methods)

In [17]:
foo(A, B::Number) = "B is a number"

foo (generic function with 5 methods)

In [18]:
foo(A::Integer, B::Integer) = "A and B are both integers"

foo (generic function with 5 methods)

In [19]:
foo(4.5, 20)

"A and B are both numbers"

In [20]:
foo(20, "Hello")

"A is a number"

In [21]:
foo(50, 100)

"A and B are both integers"

In [22]:
foo("Hello", [100,200])

"base case"

### Index: Julia - Flow Control

In [23]:
# Ternary expressions

In [24]:
A = 100

100

In [25]:
A < 20 ? "Right" : "wrong"

"wrong"

In [26]:
A > 20 ? "Right" : "wrong"

"Right"

In [27]:
# Boolean Switching expressions

In [30]:
isodd(3) && @warn("An odd Number!")

┌ Warning: An odd Number!
└ @ Main In[30]:1


In [29]:
isodd(4) && @warn("An odd Number!")

false

In [31]:
isodd(3) || @warn("An odd Number!")

true

In [32]:
isodd(4) || @warn("An odd Number!")

┌ Warning: An odd Number!
└ @ Main In[32]:1


In [33]:
@warn("An odd Number!")

┌ Warning: An odd Number!
└ @ Main In[33]:1


In [34]:
# If, elseif and else

In [35]:
fruit = "Apple"

"Apple"

In [38]:
if fruit == "Apple"
    println("I like Apple")
elseif fruit == "Banana"
    println("I like Banana.")
    println("But I prefer Apple.")
else
    println("I don't know what I like")
end

I like Banana.
But I prefer Apple.


In [37]:
fruit = "Banana"

"Banana"

In [39]:
# for loops

In [40]:
for i in 0:5:50
    println(i)
    end

0
5
10
15
20
25
30
35
40
45
50


In [44]:
c = [1]

1-element Vector{Int64}:
 1

In [45]:
# Press Ctrl + C to end
for i in c
    push!(c, i)
    @show c
    sleep(1)
    end

c = [1, 1]
c = [1, 1, 1]


LoadError: InterruptException:

In [46]:
# Loop variables

In [47]:
# Variables declared inside a loop

In [48]:
# Continue Statement

In [49]:
for x in 1:10
    if x % 4 == 0
        continue
        end
    println(x)
        end

1
2
3
5
6
7
9
10


In [50]:
# Comprehensions

In [51]:
[X^2 for X in 1:5]

5-element Vector{Int64}:
  1
  4
  9
 16
 25

In [52]:
Complex[X^2 for X in 1:5]

5-element Vector{Complex}:
  1 + 0im
  4 + 0im
  9 + 0im
 16 + 0im
 25 + 0im

In [53]:
# Enumerated arrays

In [54]:
arr = rand(0:9, 4, 4)

4×4 Matrix{Int64}:
 0  8  3  8
 6  7  5  3
 8  5  1  0
 8  9  4  1

In [55]:
[x for x in enumerate(arr)]

4×4 Matrix{Tuple{Int64, Int64}}:
 (1, 0)  (5, 8)  (9, 3)   (13, 8)
 (2, 6)  (6, 7)  (10, 5)  (14, 3)
 (3, 8)  (7, 5)  (11, 1)  (15, 0)
 (4, 8)  (8, 9)  (12, 4)  (16, 1)

In [56]:
# Zipping arrays

In [57]:
for x in zip(0:10, 100:110, 200:210)
    println(x)
    end

(0, 100, 200)
(1, 101, 201)
(2, 102, 202)
(3, 103, 203)
(4, 104, 204)
(5, 105, 205)
(6, 106, 206)
(7, 107, 207)
(8, 108, 208)
(9, 109, 209)
(10, 110, 210)


In [58]:
for x in zip(0:15, 100:110, 200:210)
    println(x)
    end

(0, 100, 200)
(1, 101, 201)
(2, 102, 202)
(3, 103, 203)
(4, 104, 204)
(5, 105, 205)
(6, 106, 206)
(7, 107, 207)
(8, 108, 208)
(9, 109, 209)
(10, 110, 210)


In [59]:
# Nested loops

In [61]:
for n in 1:3, m in 1:2
    @show (n, m)
    end

(n, m) = (1, 1)
(n, m) = (1, 2)
(n, m) = (2, 1)
(n, m) = (2, 2)
(n, m) = (3, 1)
(n, m) = (3, 2)


In [62]:
# While loops

In [64]:
n = 0
while n < 5
    println(n)
    global n += 1
    end

0
1
2
3
4


In [65]:
# Exceptions

In [66]:
str = "string";
try
    str[1] = "p"
catch e
    println("the code caught an error: $e")
    println("but we can easily continue with execution...")
end

the code caught an error: MethodError(setindex!, ("string", "p", 1), 0x0000000000007a8f)
but we can easily continue with execution...


In [67]:
str[1]

's': ASCII/Unicode U+0073 (category Ll: Letter, lowercase)

In [68]:
# Do block

In [71]:
Prime_numbers = [1,2,3,5,7,11,13,17,19,23, 19];

In [72]:
findall(x -> isequal(19, x), Prime_numbers)

2-element Vector{Int64}:
  9
 11

In [74]:
findall(Prime_numbers) do x
isequal(x, 19)
end

2-element Vector{Int64}:
  9
 11

### Index: Julia - Dictionaries and Sets

In [75]:
# Creating Dictionaries

In [78]:
first_dict = Dict("X" => 100, "Y" => 110, "Z" => 220)

Dict{String, Int64} with 3 entries:
  "Y" => 110
  "Z" => 220
  "X" => 100

In [79]:
first_dict = Dict(string(x) => sind(x) for x = 0:5:360)

Dict{String, Float64} with 73 entries:
  "285" => -0.965926
  "310" => -0.766044
  "245" => -0.906308
  "320" => -0.642788
  "350" => -0.173648
  "20"  => 0.34202
  "65"  => 0.906308
  "325" => -0.573576
  "155" => 0.422618
  "80"  => 0.984808
  "335" => -0.422618
  "125" => 0.819152
  "360" => 0.0
  "75"  => 0.965926
  "110" => 0.939693
  "185" => -0.0871557
  "70"  => 0.939693
  "50"  => 0.766044
  "190" => -0.173648
  "270" => -1.0
  "290" => -0.939693
  "115" => 0.906308
  "165" => 0.258819
  "140" => 0.642788
  "300" => -0.866025
  ⋮     => ⋮

In [80]:
first_dict = Dict("X" => 100, "Y" => 110, "Z" => 220)

Dict{String, Int64} with 3 entries:
  "Y" => 110
  "Z" => 220
  "X" => 100

In [81]:
haskey(first_dict, "Z")

true

In [82]:
haskey(first_dict, "A")

false

In [83]:
in(("X" => 100), first_dict)

true

In [84]:
in(("X" => 220), first_dict)

false

In [85]:
# Add a new key-value

In [86]:
first_dict["R"] = 400

400

In [87]:
first_dict

Dict{String, Int64} with 4 entries:
  "Y" => 110
  "Z" => 220
  "X" => 100
  "R" => 400

In [88]:
delete!(first_dict, "R")

Dict{String, Int64} with 3 entries:
  "Y" => 110
  "Z" => 220
  "X" => 100

In [89]:
keys(first_dict)

KeySet for a Dict{String, Int64} with 3 entries. Keys:
  "Y"
  "Z"
  "X"

In [90]:
values(first_dict)

ValueIterator for a Dict{String, Int64} with 3 entries. Values:
  110
  220
  100

In [91]:
for kv in first_dict
    println(kv)
    end

"Y" => 110
"Z" => 220
"X" => 100


In [92]:
# Sorting a dictionary

In [93]:
first_dict = Dict("R" => 100, "S" => 220, "T" => 350, "U" => 400, "V" => 575, "W" => 670)

Dict{String, Int64} with 6 entries:
  "S" => 220
  "U" => 400
  "T" => 350
  "W" => 670
  "V" => 575
  "R" => 100

In [94]:
for key in sort(collect(keys(first_dict)))
    println("$key => $(first_dict[key])")
    end

R => 100
S => 220
T => 350
U => 400
V => 575
W => 670


In [96]:
import Pkg; Pkg.add("DataStructures")

    Updating registry at `C:\Users\DELL\.julia\registries\General.toml`
   Resolving package versions...
   Installed OrderedCollections ─ v1.4.1
   Installed DataStructures ───── v0.18.11
   Installed Compat ───────────── v3.43.0
    Updating `C:\Users\DELL\.julia\environments\v1.7\Project.toml`
  [864edb3b] + DataStructures v0.18.11
    Updating `C:\Users\DELL\.julia\environments\v1.7\Manifest.toml`
  [34da2185] + Compat v3.43.0
  [864edb3b] + DataStructures v0.18.11
  [bac558e1] + OrderedCollections v1.4.1
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [37e2e46d] + LinearAlgebra
  [1a1011a3] + SharedArrays
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [e66e0078] + CompilerSupportLibraries_jll
  [4536629a] + OpenBLAS_jll
  [8e850b90] + libblastrampoline_jll
Precompiling project...
  ✓ OrderedCollections
  ✓ CompilerSupportLibraries_jll
  ✓ Compat
  ✓ OpenBLAS_jll
  ✓ libblastrampoline_jll
  ✓ DataStructures
  6 dependencies successfully precompiled in 5 seconds 

In [97]:
import DataStructures

In [100]:
first_dict = DataStructures.SortedDict("T" => 350, "S" => 520, "U" => 400, "V" => 575, "W" => 670)

DataStructures.SortedDict{String, Int64, Base.Order.ForwardOrdering} with 5 entries:
  "S" => 520
  "T" => 350
  "U" => 400
  "V" => 575
  "W" => 670

In [101]:
first_dict["R"] = 100

100

In [102]:
first_dict

DataStructures.SortedDict{String, Int64, Base.Order.ForwardOrdering} with 6 entries:
  "R" => 100
  "S" => 520
  "T" => 350
  "U" => 400
  "V" => 575
  "W" => 670

In [103]:
# Word Counting Example

In [126]:
f = open("nlp.txt")

IOStream(<file nlp.txt>)

In [127]:
wordlist = String[]

String[]

In [128]:
for line in eachline(f)
    words = split(line, r"\W")
    map(w -> push!(wordlist, lowercase(w)), words)
    end

In [129]:
wordlist

250-element Vector{String}:
 "if"
 "you"
 "have"
 "ever"
 "worked"
 "at"
 "a"
 "faang"
 "or"
 "even"
 "technology"
 "driven"
 "start"
 ⋮
 "steady"
 "requirement"
 "for"
 "sql"
 "skill"
 "sets"
 "for"
 "the"
 "past"
 "5"
 "years"
 ""

In [130]:
filter!(!isempty, wordlist)

225-element Vector{String}:
 "if"
 "you"
 "have"
 "ever"
 "worked"
 "at"
 "a"
 "faang"
 "or"
 "even"
 "technology"
 "driven"
 "start"
 ⋮
 "a"
 "steady"
 "requirement"
 "for"
 "sql"
 "skill"
 "sets"
 "for"
 "the"
 "past"
 "5"
 "years"

In [124]:
filter!(isempty, wordlist)

25-element Vector{String}:
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""
 ""

In [131]:
close(f)

In [132]:
wordcounts = Dict{String,Int64}()
Dict{String,Int64}()

Dict{String, Int64}()

In [133]:
for word in wordlist
    wordcounts[word]=get(wordcounts, word, 0) + 1
    end

In [134]:
for i in sort(collect(keys(wordcounts)))
    println("$i, $(wordcounts[i])")
    end

2019, 1
30, 1
5, 1
a, 6
ability, 1
about, 1
access, 2
all, 1
allowed, 1
also, 1
amount, 1
an, 1
analyst, 1
analysts, 1
and, 5
anecdotal, 1
anyone, 1
are, 1
as, 2
at, 1
average, 1
based, 1
be, 1
better, 1
both, 1
but, 1
by, 1
can, 1
cloud, 1
com, 1
come, 1
company, 1
data, 6
deal, 1
do, 1
don, 2
driven, 2
drives, 1
easily, 2
easy, 1
editor, 2
editors, 2
even, 1
ever, 1
everything, 1
experience, 1
faang, 1
fact, 2
figure, 2
for, 3
from, 1
go, 1
has, 2
hassle, 1
have, 3
here, 1
how, 1
however, 1
if, 2
importance, 1
in, 3
indeed, 1
instacart, 1
install, 1
installed, 1
interact, 1
is, 3
it, 2
just, 1
know, 2
language, 1
like, 1
longer, 1
managers, 1
managing, 1
minutes, 1
more, 1
necessity, 1
need, 2
next, 1
no, 1
now, 1
of, 4
on, 1
or, 1
out, 3
past, 1
pms, 1
point, 1
probably, 1
product, 2
queries, 1
query, 1
realized, 1
requirement, 1
run, 2
s, 2
saas, 2
section, 1
sets, 1
shown, 1
skill, 1
spends, 1
sql, 6
start, 1
starting, 1
steady, 1
t, 2
talk, 1
team, 1
technology, 1
that, 4
the, 10

In [135]:
sort(collect(wordcounts), by = tuple -> last(tuple), rev=true)

135-element Vector{Pair{String, Int64}}:
         "to" => 13
        "the" => 10
        "you" => 8
       "data" => 6
        "sql" => 6
          "a" => 6
        "and" => 5
       "that" => 4
         "of" => 4
       "want" => 3
         "is" => 3
       "have" => 3
         "in" => 3
              ⋮
 "importance" => 1
   "managing" => 1
   "interact" => 1
      "shown" => 1
        "all" => 1
        "com" => 1
   "realized" => 1
       "team" => 1
     "better" => 1
       "like" => 1
     "longer" => 1
 "understand" => 1

In [136]:
sort(collect(wordcounts), by = tuple -> last(tuple), rev=true)[1:10]

10-element Vector{Pair{String, Int64}}:
   "to" => 13
  "the" => 10
  "you" => 8
 "data" => 6
  "sql" => 6
    "a" => 6
  "and" => 5
 "that" => 4
   "of" => 4
 "want" => 3

In [137]:
filter(tuple -> startswith(first(tuple), "n") && last(tuple) < 4, collect(wordcounts))

5-element Vector{Pair{String, Int64}}:
      "need" => 2
 "necessity" => 1
        "no" => 1
       "now" => 1
      "next" => 1

In [138]:
# Sets

In [139]:
var_color = Set()

Set{Any}()

In [140]:
num_primes = Set{Int64}()

Set{Int64}()

In [141]:
var_color = Set{String}(["red","green","blue"])

Set{String} with 3 elements:
  "blue"
  "green"
  "red"

In [142]:
push!(var_color, "black")

Set{String} with 4 elements:
  "blue"
  "green"
  "black"
  "red"

In [143]:
in("red", var_color)

true

In [144]:
in("yellow", var_color)

false

In [145]:
color_rainbow = Set(["red","orange","yellow","green","blue","indigo","violet"])


Set{String} with 7 elements:
  "indigo"
  "yellow"
  "orange"
  "blue"
  "violet"
  "green"
  "red"

In [146]:
union(var_color, color_rainbow)

Set{String} with 8 elements:
  "indigo"
  "green"
  "black"
  "yellow"
  "orange"
  "blue"
  "violet"
  "red"

In [147]:
# Intersection

In [148]:
intersect(var_color, color_rainbow)

Set{String} with 3 elements:
  "blue"
  "green"
  "red"

In [149]:
# Difference

In [150]:
setdiff(var_color, color_rainbow)

Set{String} with 1 element:
  "black"

In [151]:
# Some Functions on Dictionary

In [152]:
dict1 = Dict(100=>"X", 220 => "Y")

Dict{Int64, String} with 2 entries:
  220 => "Y"
  100 => "X"

In [153]:
dict2 = Dict(220 => "Y", 300 => "Z", 450 => "W")

Dict{Int64, String} with 3 entries:
  300 => "Z"
  220 => "Y"
  450 => "W"

In [154]:
union(dict1, dict2)

4-element Vector{Pair{Int64, String}}:
 220 => "Y"
 100 => "X"
 300 => "Z"
 450 => "W"

In [155]:
intersect(dict1, dict2)

1-element Vector{Pair{Int64, String}}:
 220 => "Y"

In [156]:
setdiff(dict1, dict2)

1-element Vector{Pair{Int64, String}}:
 100 => "X"

In [157]:
merge(dict1, dict2)

Dict{Int64, String} with 4 entries:
  300 => "Z"
  220 => "Y"
  100 => "X"
  450 => "W"

In [158]:
dict1

Dict{Int64, String} with 2 entries:
  220 => "Y"
  100 => "X"

In [159]:
findmin(dict1)

("X", 100)

### Index: Julia - Date & Time

In [1]:
# Date, Time, and DateTimes

In [3]:
import Dates

In [4]:
rightnow = Dates.Time(Dates.now())

10:13:05.598

In [5]:
Dates.now()

2022-04-14T10:13:42.151

In [6]:
My_Birthday = Dates.Date(1994,2,12)

1994-02-12

In [7]:
armistice_date = Dates.DateTime(1990,11,11,11,11,11)

1990-11-11T11:11:11

In [8]:
today_date = Dates.today()

2022-04-14

In [9]:
Dates.now(Dates.UTC)

2022-04-14T04:44:51.209

In [10]:
Dates.DateTime("20180629 120000", "yyyymmdd HHMMSS")

2018-06-29T12:00:00

In [11]:
Dates.DateTime("19/07/2007 17:42", "dd/mm/yyyy HH:MM")

2007-07-19T17:42:00

In [12]:
# Queries regrading Date and Time

In [13]:
Dates.year(My_Birthday)

1994

In [14]:
Dates.month(My_Birthday)

2

In [16]:
Dates.minute(Dates.now())

17

In [17]:
Dates.hour(Dates.now())

10

In [18]:
Dates.second(Dates.now())

44

In [19]:
Dates.minute(rightnow)

13

In [20]:
Dates.hour(rightnow)

10

In [21]:
Dates.second(rightnow)

5

In [22]:
Dates.dayofweek(My_Birthday)

6

In [25]:
Dates.dayname(My_Birthday)

"Saturday"

In [26]:
Dates.yearmonthday(My_Birthday)

(1994, 2, 12)

In [27]:
# Date Arithmetic

In [28]:
today_date - My_Birthday

10288 days

In [31]:
datetimenow = Dates.now()

2022-04-14T10:44:23.651

In [32]:
datetimenow - armistice_date

991611192651 milliseconds

In [33]:
Dates.Period(today_date - My_Birthday)

10288 days

In [34]:
Dates.canonicalize(Dates.CompoundPeriod(datetimenow - armistice_date))

1639 weeks, 3 days, 23 hours, 33 minutes, 12 seconds, 651 milliseconds

In [35]:
Dates.CompoundPeriod(datetimenow - armistice_date)

991611192651 milliseconds

In [36]:
My_Birthday + Dates.Year(20) + Dates.Month(6)

2014-08-12

In [40]:
Dates.dayname(My_Birthday + Dates.Day(1))

"Sunday"

In [41]:
Dates.dayofweek(My_Birthday + Dates.Day(1))

7

In [42]:
# Range of Dates

In [43]:
date_range = Dates.Date(2000,1,1):Dates.Month(1):Dates.Date(2020,1,1)

Dates.Date("2000-01-01"):Dates.Month(1):Dates.Date("2020-01-01")

In [48]:
weekdaysfromrange = filter(dy -> Dates.dayname(dy) != "Saturday" && Dates.dayname(dy) != "Sunday" , date_range[1:10])

6-element Vector{Dates.Date}:
 2000-02-01
 2000-03-01
 2000-05-01
 2000-06-01
 2000-08-01
 2000-09-01

In [49]:
# Formatting of Dates

In [50]:
Dates.Date("Sun, 27 Sep 2020", "e, d u y")

2020-09-27

In [54]:
Dates.Date("Sun, 27 Sep 2020", "e, d u yy")

2020-09-27

In [58]:
Dates.Date("Sun, 27 Sep 2020", "e, d U y")

LoadError: ArgumentError: Unable to parse date time. Expected directive DatePart(U) at char 9

In [59]:
Dates.DateTime("Sun, 27 Sep 2020 10:25:10", "e, d u y H:M:S")

2020-09-27T10:25:10

In [60]:
# Rounding Dates and Times

In [61]:
Dates.now()

2022-04-14T11:04:09.843

In [65]:
Dates.format(round(Dates.DateTime(datetimenow), Dates.Minute(15)), Dates.RFC1123Format)

"Thu, 14 Apr 2022 10:45:00"

In [66]:
round(Dates.DateTime(datetimenow), Dates.Minute(15))

2022-04-14T10:45:00

In [68]:
round(Dates.DateTime(datetimenow), Dates.Minute(30))

2022-04-14T10:30:00

In [69]:
ceil(My_Birthday, Dates.Month)

1994-03-01

In [70]:
ceil(My_Birthday, Dates.Year)

1995-01-01

In [71]:
ceil(My_Birthday, Dates.Week)

1994-02-14

In [72]:
# Recurring Dates

In [73]:
date_range = Dates.Date(2000,1,1):Dates.Month(1):Dates.Date(2020,1,1)

Dates.Date("2000-01-01"):Dates.Month(1):Dates.Date("2020-01-01")

In [75]:
filter(d -> Dates.dayname(d) == "Sunday", date_range[1:20])

3-element Vector{Dates.Date}:
 2000-10-01
 2001-04-01
 2001-07-01

In [76]:
# Unix time

In [77]:
using Dates

In [78]:
time()

1.64991488345e9

In [79]:
Dates.unix2datetime(time())

2022-04-14T05:41:42.657

In [80]:
# Moments in time

In [81]:
moment=Dates.now()

2022-04-14T11:12:09.331

In [82]:
Dates.value(moment)

63785617929331

In [83]:
moment.instant

Dates.UTInstant{Millisecond}(Millisecond(63785617929331))

In [84]:
# Time and Monitoring

In [85]:
function foo(n)
    for i in 1:n
        x = sin(rand())
        end
    end

foo (generic function with 1 method)

In [86]:
@elapsed foo(100000000)

3.1813904

In [87]:
@time foo(100000000)

  2.979582 seconds


### Index: Julia - Files I/O

In [88]:
# Opening a text file

In [1]:
foo = open("nlp.txt")

IOStream(<file nlp.txt>)

In [4]:
# Closing the file
close(foo)

In [9]:
totaltime, totallines = 
open("nlp.txt") do foo
    linecounter = 0
    timetaken = @elapsed for l in eachline(foo)
                            linecounter += 1
                            end
(timetaken, linecounter)
end

(4.49e-5, 13)

In [10]:
# Reading a file all at once

In [11]:
ABC = open("nlp.txt") do file
        read(file, String)
        end

"If you have ever worked at a FAANG or even technology-driven start-up like Instacart, then you have probably realized that data drives everything.\r\n\r\nTo the point that analysts, PMs, and product managers are starting to understand SQL out of necessity. SQL is the languag" ⋯ 654 bytes ⋯ " access your team’s data warehouse. This has allowed anyone in the company easy access to their data.\r\n\r\nWe know both from anecdotal experience as well as the fact that indeed.com’s tracking in 2019 has shown a steady requirement for SQL skill sets for the past 5 years."

In [12]:
foo = open("nlp.txt")

IOStream(<file nlp.txt>)

In [13]:
lines = readlines(foo)

13-element Vector{String}:
 "If you have ever worked at a FA" ⋯ 84 bytes ⋯ "ed that data drives everything."
 ""
 "To the point that analysts, PMs" ⋯ 129 bytes ⋯ "ith data, you need to know it."
 ""
 "Do you want to easily figure ou" ⋯ 112 bytes ⋯ "figure out how to run a query."
 ""
 "This ability to run queries eas" ⋯ 169 bytes ⋯ "itor more in the next section."
 ""
 "However, the importance here is" ⋯ 72 bytes ⋯ " all the hassle of managing it."
 ""
 "Now you can just go to a URL an" ⋯ 73 bytes ⋯ "pany easy access to their data."
 ""
 "We know both from anecdotal exp" ⋯ 106 bytes ⋯ "ill sets for the past 5 years."

In [17]:
lines[1]

"If you have ever worked at a FAANG or even technology-driven start-up like Instacart, then you have probably realized that data drives everything."

In [14]:
# Reading line by line

In [15]:
open("nlp.txt") do file
    for ln in eachline(file)
        println("$(length(ln)), $(ln)")
        end
    end

146, If you have ever worked at a FAANG or even technology-driven start-up like Instacart, then you have probably realized that data drives everything.
0, 
190, To the point that analysts, PMs, and product managers are starting to understand SQL out of necessity. SQL is the language of data and if you want to interact with data, you need to know it.
0, 
171, Do you want to easily figure out the average amount of time a user spends on your product, but don’t want to wait for an analyst? You better figure out how to run a query.
0, 
230, This ability to run queries easily is also driven by the fact that SQL editors no longer need to be installed. With cloud-based data, warehouses come SaaS SQL editors. We will talk about a SaaS SQL editor more in the next section.
0, 
132, However, the importance here is you don’t have to wait 30 minutes to install and editor and deal with all the hassle of managing it.
0, 
133, Now you can just go to a URL and access your team’s data warehouse. This has

In [18]:
open("nlp.txt") do f
    line = 1
    while !eof(f)
        x = readline(f)
        println("$line $x")
        line += 1
        end
    end

1 If you have ever worked at a FAANG or even technology-driven start-up like Instacart, then you have probably realized that data drives everything.
2 
3 To the point that analysts, PMs, and product managers are starting to understand SQL out of necessity. SQL is the language of data and if you want to interact with data, you need to know it.
4 
5 Do you want to easily figure out the average amount of time a user spends on your product, but don’t want to wait for an analyst? You better figure out how to run a query.
6 
7 This ability to run queries easily is also driven by the fact that SQL editors no longer need to be installed. With cloud-based data, warehouses come SaaS SQL editors. We will talk about a SaaS SQL editor more in the next section.
8 
9 However, the importance here is you don’t have to wait 30 minutes to install and editor and deal with all the hassle of managing it.
10 
11 Now you can just go to a URL and access your team’s data warehouse. This has allowed anyone in th

In [19]:
# Information about file

In [20]:
for n in fieldnames(typeof(stat("nlp.txt")))
    println(n, ": ", getfield(stat("nlp.txt"),n))
    end

desc: nlp.txt
device: 3763111938
inode: 21962
mode: 33206
nlink: 1
uid: 0
gid: 0
rdev: 0
size: 1199
blksize: 4096
blocks: 8
mtime: 1.649871914040285e9
ctime: 1.649871914040285e9


In [21]:
stat("nlp.txt")

StatStruct for "nlp.txt"
   size: 1199 bytes
 device: 3763111938
  inode: 21962
   mode: 0o100666 (-rw-rw-rw-)
  nlink: 1
    uid: 0
    gid: 0
   rdev: 0
  blksz: 4096
 blocks: 8
  mtime:  (18 hours ago)
  ctime:  (18 hours ago)

In [23]:
fieldnames(typeof(stat("nlp.txt")))

(:desc, :device, :inode, :mode, :nlink, :uid, :gid, :rdev, :size, :blksize, :blocks, :mtime, :ctime)

In [24]:
stat("nlp.txt")

StatStruct for "nlp.txt"
   size: 1199 bytes
 device: 3763111938
  inode: 21962
   mode: 0o100666 (-rw-rw-rw-)
  nlink: 1
    uid: 0
    gid: 0
   rdev: 0
  blksz: 4096
 blocks: 8
  mtime:  (18 hours ago)
  ctime:  (18 hours ago)

In [25]:
# Writing to files

In [26]:
test_numbers = rand(10,10)

10×10 Matrix{Float64}:
 0.163474   0.824215  0.811395   0.0055132  …  0.248566  0.292216   0.22936
 0.243101   0.921736  0.176488   0.632088      0.633844  0.429399   0.206233
 0.06222    0.686222  0.656108   0.0399315     0.298016  0.202332   0.589878
 0.0339912  0.674568  0.181702   0.324654      0.377552  0.51069    0.410556
 0.34974    0.61265   0.300722   0.974915      0.32244   0.828844   0.563504
 0.660009   0.189778  0.554863   0.420013   …  0.480785  0.380315   0.793779
 0.266477   0.31251   0.960764   0.104427      0.889184  0.482064   0.0992443
 0.406758   0.313713  0.989346   0.0882647     0.183502  0.0293375  0.178762
 0.248917   0.394669  0.0324198  0.96864       0.99695   0.899873   0.534108
 0.0684438  0.75115   0.0788829  0.51221       0.704432  0.315249   0.222963

In [28]:
import DelimitedFiles

In [30]:
DelimitedFiles.writedlm("write_testfile.txt", test_numbers)

### Index: Julia Programming - Metaprogramming

In [31]:
# Stage 1 − Raw Julia code is parsed
# Stage 2 − Parsed Julia code is executed

In [32]:
ABC = 100

100

In [33]:
:ABC

:ABC

In [34]:
:(100-50)

:(100 - 50)

In [38]:
quote
    100 - 50
    end

quote
    #= In[38]:2 =#
    100 - 50
end

In [39]:
expression = quote
    for x = 1:5
        println(x)
        end
    end

quote
    #= In[39]:2 =#
    for x = 1:5
        #= In[39]:3 =#
        println(x)
    end
end

In [40]:
typeof(expression)

Expr

In [41]:
# Evaluated expressions