In [1]:
import scipy.io
mat = scipy.io.loadmat('../data/tasmax_tasmin_imd_1951_2020.mat')

In [2]:
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Mon Jul 26 19:02:44 2021',
 '__version__': '1.0',
 '__globals__': [],
 'tasmax_imd_1951_2020': array([[[99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         ...,
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9]],
 
        [[99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         ...,
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9]],
 
        [[99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         [99.9, 99.9, 99.9, ..., 99.9, 99.9, 99.9],
         ...,
         

In [3]:
mat['tasmax_imd_1951_2020'].shape

(25568, 31, 31)

In [4]:
import pandas as pd
import numpy as np

In [5]:
# Latitude range
np.arange(7.5, 38.5, 1)

array([ 7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5,
       18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5,
       29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5])

In [6]:
# Longitude range
np.arange(67.5, 98.5, 1)

array([67.5, 68.5, 69.5, 70.5, 71.5, 72.5, 73.5, 74.5, 75.5, 76.5, 77.5,
       78.5, 79.5, 80.5, 81.5, 82.5, 83.5, 84.5, 85.5, 86.5, 87.5, 88.5,
       89.5, 90.5, 91.5, 92.5, 93.5, 94.5, 95.5, 96.5, 97.5])

In [7]:
# 28.5 N, 78.5 E --> Index is (21, 11)

In [ ]:
# Taking Max Temperatures in a series

In [24]:
tasmax_imd_1951_2020_lat21_long11 = mat['tasmax_imd_1951_2020'][:,21,11]

In [25]:
len(tasmax_imd_1951_2020_lat21_long11)

25568

In [26]:
tasmax_imd_1951_2020_lat21_long11

array([29.52      , 28.41      , 28.04      , ..., 29.83602905,
       29.30597496, 28.85953522])

In [27]:
# Taking Min Temperatures in a series

In [28]:
tasmin_imd_1951_2020_lat21_long11 = mat['tasmin_imd_1951_2020'][:,21,11]

In [29]:
len(tasmin_imd_1951_2020_lat21_long11)

25568

In [30]:
tasmin_imd_1951_2020_lat21_long11

array([16.06      , 14.73      , 13.6       , ..., 15.88205433,
       17.06483078, 18.24519348])

In [17]:
import calendar
import datetime

In [18]:
df_combined_1951_2020_lat21_long11 = pd.DataFrame()

In [19]:
col_year = []
col_day_of_year = []

for year in range(1951, 2021):
    if calendar.isleap(year):
        col_year = col_year + [year]*366
        col_day_of_year = col_day_of_year + list(range(1, 367))
    else:
        col_year = col_year + [year]*365
        col_day_of_year = col_day_of_year + list(range(1, 366))

In [31]:
df_combined_1951_2020_lat21_long11['year'] = col_year
df_combined_1951_2020_lat21_long11['day_of_year'] = col_day_of_year
df_combined_1951_2020_lat21_long11['max_temp'] = list(tasmax_imd_1951_2020_lat21_long11)
df_combined_1951_2020_lat21_long11['min_temp'] = list(tasmin_imd_1951_2020_lat21_long11)

In [37]:
df_combined_1951_2020_lat21_long11['date'] = df_combined_1951_2020_lat21_long11.apply(lambda x: \
                                datetime.datetime.strptime('{} {}'.format(int(x.day_of_year), int(x.year)),'%j %Y'), axis=1)

In [60]:
df_combined_1951_2020_lat21_long11['month'] = df_combined_1951_2020_lat21_long11['date'].apply(lambda x: x.month)

In [44]:
df_combined_1951_2020_lat21_long11 = df_combined_1951_2020_lat21_long11[['year', 'day_of_year', 'date', 'month', 'max_temp', 'min_temp']]

In [63]:
df_combined_1951_2020_lat21_long11['diff_max_min'] = df_combined_1951_2020_lat21_long11['max_temp'] - \
                                                             df_combined_1951_2020_lat21_long11['min_temp']    

In [64]:
df_combined_1951_2020_lat21_long11

year  day_of_year       date  month   max_temp   min_temp  diff_max_min
0      1951            1 1951-01-01      1  29.520000  16.060000     13.460000
1      1951            2 1951-01-02      1  28.410000  14.730000     13.680000
2      1951            3 1951-01-03      1  28.040000  13.600000     14.440000
3      1951            4 1951-01-04      1  28.210000  14.500000     13.710000
4      1951            5 1951-01-05      1  28.960000  15.360000     13.600000
...     ...          ...        ...    ...        ...        ...           ...
25563  2020          362 2020-12-27     12  29.906174  15.237489     14.668685
25564  2020          363 2020-12-28     12  30.160309  15.461741     14.698567
25565  2020          364 2020-12-29     12  29.836029  15.882054     13.953975
25566  2020          365 2020-12-30     12  29.305975  17.064831     12.241144
25567  2020          366 2020-12-31     12  28.859535  18.245193     10.614342

[25568 rows x 7 columns]

In [50]:
df_combined_1951_2020_lat21_long11_filtered = df_combined_1951_2020_lat21_long11[\
                (df_combined_1951_2020_lat21_long11['year']>=1980) & (df_combined_1951_2020_lat21_long11['year']<=2013)
            & (df_combined_1951_2020_lat21_long11['month']>=3) & (df_combined_1951_2020_lat21_long11['month']<=6)]

In [51]:
df_combined_1951_2020_lat21_long11_filtered

year  day_of_year       date  month  max_temp  min_temp
10652  1980           61 1980-03-01      3     37.08     21.57
10653  1980           62 1980-03-02      3     36.17     20.71
10654  1980           63 1980-03-03      3     35.56     20.29
10655  1980           64 1980-03-04      3     36.89     20.62
10656  1980           65 1980-03-05      3     37.46     21.44
...     ...          ...        ...    ...       ...       ...
22822  2013          177 2013-06-26      6     33.79     24.07
22823  2013          178 2013-06-27      6     34.88     23.50
22824  2013          179 2013-06-28      6     35.56     23.06
22825  2013          180 2013-06-29      6     34.89     23.31
22826  2013          181 2013-06-30      6     34.58     23.80

[4148 rows x 6 columns]

In [ ]:
df_combined_1951_2020_lat21_long11_filtered.to_csv('df_combined_1951_2020_lat21_long11_filtered.csv', index=False)

#### Old Format

In [13]:
# Creating DataFrame for Max temp
df_tasmax_imd_1951_2020_lat21_long11 = pd.DataFrame()

start = 0

for year in range(1951, 2021):
    if calendar.isleap(year):
        end = start + 366
        col_tmp = list(tasmax_imd_1951_2020_lat21_long11[start:end])
        df_tasmax_imd_1951_2020_lat21_long11[str(year)] = col_tmp
        start = start + 366
    else:
        end = start + 365
        col_tmp = list(tasmax_imd_1951_2020_lat21_long11[start:end]) + ['NA']
        df_tasmax_imd_1951_2020_lat21_long11[str(year)] = col_tmp
        start = start + 365
    

In [19]:
# Creating DataFrame for Min temp
df_tasmin_imd_1951_2020_lat21_long11 = pd.DataFrame()

start = 0

for year in range(1951, 2021):
    if calendar.isleap(year):
        end = start + 366
        col_tmp = list(tasmin_imd_1951_2020_lat21_long11[start:end])
        df_tasmin_imd_1951_2020_lat21_long11[str(year)] = col_tmp
        start = start + 366
    else:
        end = start + 365
        col_tmp = list(tasmin_imd_1951_2020_lat21_long11[start:end]) + ['NA']
        df_tasmin_imd_1951_2020_lat21_long11[str(year)] = col_tmp
        start = start + 365

In [22]:
df_tasmax_imd_1951_2020_lat21_long11.to_csv('df_tasmax_imd_1951_2020_lat21_long11.csv', index=False)

In [23]:
df_tasmin_imd_1951_2020_lat21_long11.to_csv('df_tasmin_imd_1951_2020_lat21_long11.csv', index=False)